### ISSUE TITLE
Clean up the angular page and name navbar as todo app

### ISSUE THREAD

**Issue by hacktoberfest-maintainer** [hacktoberfest-maintainer/angular-to-do-app#1]
![image](https://user-images.githubusercontent.com/115368282/194752502-44d1b838-43df-47b6-82ee-082e71ca3a06.png)

**Comment by Darainn** [comment]
@hacktoberfest-maintainer assign me this issue

**Comment by hacktoberfest-maintainer** [comment]
@Darainn go ahead
